/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package degiteldiary;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message.RecipientType;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjeev
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
       // initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        regestersection = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpassword = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        branch = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlable = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        rollno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        mon = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        agree = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        loginsection = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        loginpass = new javax.swing.JPasswordField();
        forgetS = new javax.swing.JButton();
        forgetarea = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        forgetfeild = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelResponse = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regestersection.setBackground(new java.awt.Color(0, 255, 255));
        regestersection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        regestersection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NEW USER REGESTER HERE");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 2, true));
        regestersection.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 260, 40));

        cpassword.setBackground(new java.awt.Color(255, 255, 204));
        cpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cpassword.setForeground(new java.awt.Color(0, 0, 102));
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });
        regestersection.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 250, 40));

        fullname.setBackground(new java.awt.Color(255, 255, 204));
        fullname.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        fullname.setForeground(new java.awt.Color(0, 0, 102));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        regestersection.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 250, 40));

        branch.setBackground(new java.awt.Color(255, 255, 204));
        branch.setFont(new java.awt.Font("Myriad Pro Light", 1, 16)); // NOI18N
        branch.setForeground(new java.awt.Color(0, 51, 255));
        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch", "Computer Science & Engineering", "Information Technology", "Mechnical Engineering", "Electronic And Telecom. Engineering", "Electrical Engineering", "Industrial And Production Engineering", "Civil Engineering" }));
        branch.setFocusCycleRoot(true);
        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });
        regestersection.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 250, 30));

        semester.setBackground(new java.awt.Color(255, 255, 204));
        semester.setFont(new java.awt.Font("Myriad Pro Light", 1, 18)); // NOI18N
        semester.setForeground(new java.awt.Color(0, 51, 255));
        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem", "1", "2", "3", "4", "5", "6", "7", "8" }));
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        regestersection.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 250, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("roll no.");
        regestersection.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("conform password");
        regestersection.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 20));

        jlable.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jlable.setForeground(new java.awt.Color(255, 0, 51));
        jlable.setText(" fullname");
        regestersection.add(jlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 26));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("branch");
        regestersection.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 26));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("GENDER");
        regestersection.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, 26));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("SUBMIT");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        regestersection.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 120, 40));

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        regestersection.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 250, 40));

        rollno.setBackground(new java.awt.Color(255, 255, 204));
        rollno.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        rollno.setForeground(new java.awt.Color(0, 0, 102));
        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        regestersection.add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, 40));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("password");
        regestersection.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        year.setToolTipText("day");
        regestersection.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 90, 30));

        day.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setToolTipText("day");
        regestersection.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 60, 30));

        mon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec" }));
        mon.setToolTipText("day");
        regestersection.add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 80, 30));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("semester");
        regestersection.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "OBC CL", "OBC NCL", "SC", "ST" }));
        regestersection.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 250, 30));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("dob");
        regestersection.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 40));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gender", "Male", "Female", "Other" }));
        regestersection.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 100, 30));

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("CATEGORY");
        regestersection.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 26));

        agree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agreeKeyPressed(evt);
            }
        });
        regestersection.add(agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, 30));

        jLabel16.setText("agree , All The Information was given here is true.");
        regestersection.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 290, 30));

        jPanel1.add(regestersection, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 510, 740));

        loginsection.setBackground(new java.awt.Color(0, 255, 255));
        loginsection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ALREADY REGESTER LOGIN HERE");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));

        loginuser.setBackground(new java.awt.Color(255, 255, 204));
        loginuser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        loginuser.setForeground(new java.awt.Color(0, 0, 102));
        loginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginuserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PASSWORD");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("ROLL NO. -");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("LOGIN");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        loginpass.setBackground(new java.awt.Color(255, 255, 204));

        forgetS.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        forgetS.setForeground(new java.awt.Color(0, 0, 153));
        forgetS.setText("forget username/password");
        forgetS.setContentAreaFilled(false);
        forgetS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetSMouseClicked(evt);
            }
        });
        forgetS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetSActionPerformed(evt);
            }
        });

        forgetarea.setBackground(new java.awt.Color(0, 255, 204));
        forgetarea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "forget section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel13.setText("enter your rollno:");

        forgetfeild.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        forgetfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetfeildActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        jButton3.setText("Update password");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        jButton4.setText("forget password");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelResponse.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout forgetareaLayout = new javax.swing.GroupLayout(forgetarea);
        forgetarea.setLayout(forgetareaLayout);
        forgetareaLayout.setHorizontalGroup(
            forgetareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgetareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forgetareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgetareaLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgetareaLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(forgetareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgetfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(forgetareaLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgetareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        forgetareaLayout.setVerticalGroup(
            forgetareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgetareaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgetfeild, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(forgetareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(46, 46, 46)
                .addComponent(jLabelResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginsectionLayout = new javax.swing.GroupLayout(loginsection);
        loginsection.setLayout(loginsectionLayout);
        loginsectionLayout.setHorizontalGroup(
            loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginsectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginsectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(loginsectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginsectionLayout.createSequentialGroup()
                        .addGroup(loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginuser, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginsectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(forgetS))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginsectionLayout.createSequentialGroup()
                        .addComponent(forgetarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        loginsectionLayout.setVerticalGroup(
            loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginsectionLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginuser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(loginsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginpass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgetS, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgetarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(loginsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 500, 750));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/degiteldiary/jec milan.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/degiteldiary/jecacmlogo.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 290, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1454, 861));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginuserActionPerformed

    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswordActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         String name = fullname.getText();
         String Rollno=rollno.getText();
         String Password = password.getText();
         String Cpass = cpassword.getText();
         String Branch = (String) branch.getSelectedItem();
         String Semester = (String) semester.getSelectedItem();
         String dob=(String)day.getSelectedItem()+"/"+mon.getSelectedItem()+"/"+year.getSelectedItem();
         String cast=(String) category.getSelectedItem();
         String Gender=(String) gender.getSelectedItem();
         
         
         
         
         
       
         if(name.equals(""))
         {
             JOptionPane.showMessageDialog(null,"PLEASE FULLNAME","ERROR",JOptionPane.ERROR_MESSAGE);
         }
         else if(Rollno.equals(""))
         {
             JOptionPane.showMessageDialog(null,"PLEASE ENTER ROLLNO","ERROR",JOptionPane.ERROR_MESSAGE); 
         }
         else if(Password.equals(""))
         {
              JOptionPane.showMessageDialog(null,"PLAESE ENTER PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);
         }
         else if(Password == null ? Cpass != null : !Password.equals(Cpass))
         {
           JOptionPane.showMessageDialog(null,"PASSWORD DOES NOT MATCH ENTER CORRECT PASSWORD","ERROR",JOptionPane.ERROR_MESSAGE);   
         }
         else if(Branch.equals("Branch"))
         {
             JOptionPane.showMessageDialog(null,"PLEASE SELECT YOUR BRANCH","ERROR",JOptionPane.ERROR_MESSAGE);
         }
         else if(Semester.equals("Sem"))
         {
             JOptionPane.showMessageDialog(null,"PLEASE SELECT YOUR CURRENT SEMESTER","ERROR",JOptionPane.ERROR_MESSAGE);
         }
         else if(dob.equals("day/month/year")){
             
               JOptionPane.showMessageDialog(null," PLEASE ENTER YOUR CORRECT DATE OF BIRTH","ERROR",JOptionPane.ERROR_MESSAGE);
             
         }
         
         else if(Gender.equals("gender"))
         {
              JOptionPane.showMessageDialog(null,"PLEASE SELECT GENDER","ERROR",JOptionPane.ERROR_MESSAGE);
         }
         else if(!(agree.isSelected()))
         {
          JOptionPane.showMessageDialog(null,"ACCEPT TERM & CONDITION","ERROR",JOptionPane.ERROR_MESSAGE);   
         }
         
         else 
         {
             PreparedStatement pst;
             
             String query= "INSERT INTO `studentsignup`(`FULLNAME`, `ROLLNO`, `PASSWORD`, `BRANCH`, `SEMESTER`, `DOB`, `CAST`) VALUES (?,?,?,?,?,?,?)";
             
             try {
                 
                 
                 pst=connecter.newdata().prepareStatement(query);
                 
                 pst.setString(1,name);
                 pst.setString(2,Rollno);
                 pst.setString(3,Password);
                 pst.setString(4,Branch);
                 pst.setString(5,Semester);
                 pst.setString(6, dob);
                 pst.setString(7, cast);
                 
                  if (pst.executeUpdate()>0)
                       {
                           JOptionPane.showMessageDialog(null,"CONGRATULATION !!  YOU ARE REGESTER IN COLLEGE PORTAL SUCESSFULLY");
                          
                       }
                 
                 
                 
                 
                 
             } catch (Exception e) {
                 
             }
             
         }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String Loginuser = loginuser.getText();
        String Loginpass = loginpass.getText();
        
        
        PreparedStatement ps;
        ResultSet rs;
        
        String query1 ="SELECT * FROM `studentsignup` WHERE ROLLNO=? AND PASSWORD=?";
        
        try {
            ps=connecter.newdata().prepareStatement(query1);
            
            ps.setString(1,Loginuser);
            ps.setString(2,Loginpass);
            
            
            rs=ps.executeQuery();
            
             if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"LOGIN SUCESSFUL WELCOME IN JEC ");
                studentsection ss = new studentsection();
                ss.setVisible(true);
                
                setVisible(false);
                
                
                
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"INVALID UESRID AND PASSWORD / DONT HAVE ACCOUNT REGESTER FIRST","ERROR",JOptionPane.ERROR_MESSAGE);
            }
                    
                    
                    
                    
        } catch (Exception e) {
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void agreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agreeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreeKeyPressed

    private void forgetfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetfeildActionPerformed

    private void forgetSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetSActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_forgetSActionPerformed

    private void forgetSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetSMouseClicked
        // TODO add your handling code here:
        new student().forgetarea.setVisible(false);
        
    }//GEN-LAST:event_forgetSMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(forgetfeild.equals(null))
        {
            JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR NUMBER FIRST ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
       
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(forgetfeild.equals(null))
        {
            JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR NUMBER FIRST ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        else{
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", 465);
        props.put("mail.smtp.user", "ssanjeev9696@gmail.com");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", 465);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false"); 
        try {
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/collegeportal","root","");
            String query = "select PASSWORD from studentsignup where ROLLNO LIKE '"+forgetfeild.getText().trim()+"'";
           
             PreparedStatement statmntuserid = con.prepareStatement(query);
            ResultSet result = statmntuserid.executeQuery();       
           
            if (result.next())
            {   
                String fetchedpassword = result.getString("PASSWORD"); 
                
                Session session = Session.getDefaultInstance(props, null);
                session.setDebug(true);
                MimeMessage message = new MimeMessage(session);
                message.setText("YOUR PASSWORD IS - " + fetchedpassword);
                
                message.setSubject("JABALPUR ENGINEERING COLLEGE JEC ");
                message.setFrom(new InternetAddress("ssanjeev9696@gmail.com"));
                message.addRecipient(RecipientType.TO, new InternetAddress(forgetfeild.getText().trim()));
                message.saveChanges();
                Transport transport = session.getTransport("smtp");
                transport.connect("smtp.gmail.com", "ssanjeev9696@gmail.com", "29042000 SANJ");
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
                jLabelResponse.setText("Your password mailed to your email id");         
            }
        } catch (Exception e) {
            e.printStackTrace();  
            jLabelResponse.setText("Email Address not found");
            
        }  
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                 
                new student().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agree;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField cpassword;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton forgetS;
    private javax.swing.JPanel forgetarea;
    private javax.swing.JTextField forgetfeild;
    private javax.swing.JTextField fullname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelResponse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlable;
    private javax.swing.JPasswordField loginpass;
    private javax.swing.JPanel loginsection;
    private javax.swing.JTextField loginuser;
    private javax.swing.JComboBox<String> mon;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel regestersection;
    private javax.swing.JTextField rollno;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
